# Generated by Django 4.1.6 on 2023-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(default='', max_length=70)),
                ('designation', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('contactno', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
