# Generated by Django 4.1.6 on 2023-07-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollmentid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('studentname', models.CharField(default='', max_length=150)),
                ('batchyear', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=150)),
                ('contactno', models.CharField(default='', max_length=70)),
                ('studentstatus', models.CharField(default='', max_length=70)),
                ('studentsem', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
