# Generated by Django 4.1.6 on 2023-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmissionStudent',
            fields=[
                ('assignementid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('enrollmentid', models.CharField(default='', max_length=70)),
                ('url', models.CharField(default='', max_length=150)),
                ('uploaddate', models.CharField(default='', max_length=70)),
                ('uploadtime', models.CharField(default='', max_length=70)),
                ('remarks', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
