# Generated by Django 4.1.6 on 2023-07-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0005_assignmentsubmissionstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmissionTeacher',
            fields=[
                ('assignemenid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('courseid', models.CharField(default='', max_length=70)),
                ('teacherid', models.CharField(default='', max_length=70)),
                ('uploaddate', models.CharField(default='', max_length=70)),
                ('startdate', models.CharField(default='', max_length=70)),
                ('enddate', models.CharField(default='', max_length=70)),
                ('url', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
