# Generated by Django 4.1.6 on 2023-07-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0006_assignmentsubmissionteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmissionteacher',
            old_name='assignemenid',
            new_name='assignementid',
        ),
    ]
