# Generated by Django 4.1.6 on 2023-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0007_rename_assignemenid_assignmentsubmissionteacher_assignementid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(default='', max_length=70)),
                ('mobileno', models.CharField(default='', max_length=150)),
                ('emailid', models.CharField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
