# Generated by Django 4.1.6 on 2023-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0008_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teacherid',
            field=models.CharField(default='', max_length=70),
        ),
    ]
