# Generated by Django 4.1.6 on 2023-07-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0009_teachers_teacherid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollmentid',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_id',
            field=models.CharField(default='', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionstudent',
            name='remarks',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='eid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacherid',
            field=models.CharField(default='', max_length=70, primary_key=True, serialize=False),
        ),
    ]
