# Generated by Django 4.1.6 on 2023-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0010_remove_student_enrollmentid_remove_teachers_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmissionteacher',
            old_name='courseid',
            new_name='coursename',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='courseid',
            new_name='coursename',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
    ]
